### PR TITLE
Style for CTA section

### LINKED ISSUE #41: style the CTA section
Image

### PR DESCRIPTION
**Pull request by asthabh23**
Fix #41 

Test URLs:
- Before: https://main--delta--hxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
- After: https://issue-41--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview

Note: This PR also has a fix for buttons "DISCOVER ALL CARDS" and "Benefits Terms"

### CODE REVIEW

**Comment by ramboz** [comment]
It seems my work on the references have leaked into that button as I see a `small` tag being added. I'll have a look today and try to fix that.

I think we can probably style the button as "bold" in the doc and mark it as cta variant in the button decoration.
So we essentially have 3 button variants:
- regular => .button
- bold => .button.cta
- italic => .button.secondary

**Comment by asthabh23** [comment]
@ramboz , I saw the [main](https://main--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview) branch for this site, and seems the buttons are already in place based on your changes. Shall I close this PR?

**Comment by ramboz** [comment]
@asthabh23 I styled the buttons alone, but haven't looked at the spacing/margin for the cta section (that david decorated with the eyebrow class already). There might be some adjustments needed.

**Comment by ramboz** [comment]
@asthabh23 I took the liberty to update this PR during your sick leave with the changes I had already committed for the buttons, and also fixed the eyebrow decoration from David. Happy to discuss and revisit this once you are back

**Pull request merged**
