### PR TITLE
feat: add accessibility quick links

### LINKED ISSUE #115: Implement skip to content a11y links
The Delta webpage uses accessibility short links "Skip to content":

Image
Image

We need to implement those as well.
- links need to be out of viewport by default (not `display: none`) so that they are not visible to regular users but still picked up by assistive technologies
- when explicitly focused via "Tab", they need to show up in the viewport
- when clicked (or by pressing space on the keyboard) we need to scroll to the main content, and shift the focus to main content as well so the next "Tab" continues from the main heading (and does not continue in the header)

### PR DESCRIPTION
**Pull request by ramboz**
Add quick navigation links for accessibility compliance.

Fix #115 

Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
- After: https://issue-115--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview

### CODE REVIEW

**Comment by ramboz** [comment]
Screenshot 2023-03-27 at 4 51 20 PM
Screenshot 2023-03-27 at 4 51 13 PM

**Review by asthabh23 — COMMENTED** [review]
Hi @ramboz , I am unable to find the comparison of this on the original delta site.
Also, as per the screenshots that you have shared, ideally there should be a red button visible which when clicked drags the focus a bit to the middle of the page.

But i see it first as a blue colored text as below
Screenshot 2023-03-28 at 6 06 16 PM

which once clicked converts to red button as below
Screenshot 2023-03-28 at 6 07 09 PM

and when its clicked the third time, then the focus changes.

Since I am unable to get the reference of it on original site, I am not sure what I need to check and if above is the expected workflow. Could you please elaborate on the expected functionality?

**Comment by ramboz** [comment]
@asthabh23 A few notes I should have added initially:

1. The live implementation is not consistent to begin with between mobile and desktop, and since this isn't really something that would show up on regular navigation, I simplified the CSS (no point in wasting extra bytes for something that is not really supposed to be visible).
2. Since this is usually triggered via assistive technologies and keyboard navigation, it's not immediately visible on the page and you'd have to "tab" your way to it. The easiest to trigger it is probably just to click the header once (somewhere on the blue background) and SHIFT+Tab back until you hit the link focus

Here is a live vs. PR comparison of the 2:
| | delta.com | PR |
|-|-|-|
|mobile|Screenshot 2023-03-28 at 7 45 00 AM|Screenshot 2023-03-28 at 7 47 42 AM|
|desktop|Screenshot 2023-03-28 at 7 47 21 AM|Screenshot 2023-03-28 at 7 47 54 AM|

**Review by askayastha22 — APPROVED** [review]
@ramboz Tested this on iPhone!

**Comment by asthabh23** [comment]
> * https://issue-115--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview

Thanks for the detailed explanation on this @ramboz . I could now actually follow it. 
Though it's now not visible as red button over the hero image, rather hidden behind the section menu below header. I guess that's the actual place it has to be at, right?
Rest, seems fine to me.

**Review by asthabh23 — APPROVED** [review]

**Pull request merged**
